# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 
email: soghrakhademi@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
 صغری خادمی هستم دانشجوی ترم 6 نرم افزار این سایت یک سایت آموزشی میباشد امیدوارم که مطالب آن مفید واقع شود
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://s-khademi.ir" # the base hostname & protocol for your site
twitter_username: 
github_username:  skhademi.github.io

# Build settings
markdown: kramdown
